---
- name: cUrl node setup
  shell: curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -

- name: Install node
  apt: name="{{ item }}" state="latest" update_cache=yes
  become: yes
  with_items: "{{ packages }}"

- name: Install node demon globally
  become: yes
  npm: name={{ item }} global=yes
  with_items: "{{ node_packages }}"

- name: Make SudRekt directory
  become: yes
  shell: mkdir /home/vagrant/SudRekt

- name: Copy files out of shared volume
  become: yes
  shell: cp -R /home/vagrant/project/* /home/vagrant/SudRekt

- name: Start server
  shell: node /home/vagrant/SudRekt/cli.js -S
...
