---
- name: cUrl node setup
  shell: curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -

- name: Install node
  apt: name="{{ item }}" state="latest" update_cache=yes
  become: yes
  with_items: "{{ packages }}"

- name: Install node demon globally
  become: yes
  npm: name=nodemon global=yes
...
