version: "3"
services: 
  db-mongo:
    image: mvertes/alpine-mongo:latest
    networks: 
      - back-tier
    volumes:
      - db-data:/data/db
  backend:
    build: .
    command: nodemon . --exitcrash
    volumes:
      - .:/app
      - dependencies:/app/node_modules
    links: 
      - db-mongo
    environment:
      - MONGO_HOST=db-mongo
      - NODE_ENV=development
    networks:
      - front-tier
      - back-tier
networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
volumes:
  dependencies:
  db-data:

